### ISSUE TITLE
ctest failure in ectrans_test_transi_memory

### ISSUE THREAD

**Issue by DJDavies2** [ecmwf-ifs/ectrans#38]
This ctest fails as follows:

144/156 Test #151: ectrans_test_transi_memory ................................................***Failed    0.12 sec
Initially allocated: 0.000000 KB
iteration 1
Allocated in iteration:       7.345215 MB
Possibly leaked in iteration: 39.234375 KB
iteration 2
Allocated in iteration:       7.305069 MB
Possibly leaked in iteration: 2.125000 KB
ERROR: Assertion `allocated()-start_iter == 0' failed @/home/h01/david.davies/cylc-run/EctransTransiFailure/share/mo-bundle/ectrans/tests/transi/transi_test_memory.c:63

This failure occurred on a Cray machine, gnu 12.1.0

**Comment by wdeconinck** [comment]
Hi @DJDavies2 Thank you for this report. Please could you provide more information on the build-type or compile flags used?

**Comment by wdeconinck** [comment]
@DJDavies2 I managed to reproduce the failed test on LUMI (Cray) with gcc 12.2.0
I got this nice warning when loading this environment there:

> gcc/12.2.0:
Other Cray sites have reported that gcc/12.2.0 can cause inconsistent results, especially
at high optimisation levels. There are also known problems with the installation on LUMI
when used in combination with the Cray wrappers (at least for C++, and likely similar
problems for GNU Fortran) because at runtime it is forced to use libraries from an older
gcc version. Use at your own risk.

When adapting the test with more iterations it seems that the `allocated()-start_iter` result oscillates between iterations around 0. Sometimes more, sometimes less. I think this must be specific to the Cray environment doing specific malloc optimisations perhaps. When investigating with valgrind I don't see any memory leak present from trans.

On this same Cray platform, the problem is also there with gcc/11.2.0 but not with the Cray compiler itself (tested cce/15.01).

We can probably ignore this failing test. I can include a mechanism to do so.

**Comment by DJDavies2** [comment]
I tried the branch, the ectrans_test_transi_memory test now works and the -DENABLE_MEMORY_TESTS=OFF option does work to disable the tests.  I am getting failures in other tasks but I don't know if that is relevant here?

**Comment by wdeconinck** [comment]
I don't think this change has to result in other failed tests, but please do mention what the failures are

**Comment by DJDavies2** [comment]
For instance there is this:

ectrans_test_benchmark_dp_T47_O48_mpi2_omp1_nfld0:

......
norm zspvor(    1)     =    1.414213562373095        error =  0.000E+00
norm zspdiv(    1,:)   =    1.414213562373095        error =  0.000E+00
norm zspsc3a(   1,:,1) =    1.414213562373095        error =  0.133E-14
norm zspsc2(    1,:)   =    1.414213562373095        error =  0.133E-14

max error zspvor(1:nlev,:)    =  0.000E+00
max error zspdiv(1:nlev,:)    =  0.000E+00
max error zspsc3a(1:nlev,:,1) =  0.133E-14
max error zspsc2(1:1,:)       =  0.133E-14

max error combined =          =  0.133E-14

MPICH ERROR [Rank 1] [job id 07a54a09-a525-40fb-af48-56e6cfbccfc4] [Thu Sep  7 12:25:44 2023] [nid001189] - Abort(536897039) (rank 1 in comm 0): Fatal error in MPIDI_Cray_shared_mem_coll_bcast: Other MPI error, error stack:
MPIDI_Cray_shared_mem_coll_bcast(422): message sizes do not match across processes in the collective routine: Received 4 but expected 8

aborting job:
Fatal error in MPIDI_Cray_shared_mem_coll_bcast: Other MPI error, error stack:
MPIDI_Cray_shared_mem_coll_bcast(422): message sizes do not match across processes in the collective routine: Received 4 but expected 8
nid001189: rank 1 exited with code 255

**Comment by wdeconinck** [comment]
I have identified the MPI issue. Strangely this (real bug) was only apparent for the Cray. It is fixed in commit 03e3282 in develop branch now. Thanks for reporting!

**Comment by DJDavies2** [comment]
Thanks, the tests all passed for me now.
